version: '3'

services:
  web:
    image: node:14
    working_dir: /home/node/app
    user: root
    ports:
      - 8080:8080
    environment:
      PUBLISH_SECRET_URI: /new
      KEY_NAME_RANDOM_BYTES: 10
      DOMAIN: localhost:8080
      PORT: 8080
      HTTP_TIMEOUT_MS: 5000
      MAX_UPLOAD_KB: 128
    volumes:
      - ./:/home/node/app
    command: >
      bash -c "npm install && node dist/bin/cli.js"
